[@ww.textfield labelKey="com.scrumtech.octopus.serverUrl" name="serverUrl" required='true'/]
[@ww.textfield labelKey="com.scrumtech.octopus.apiKey" name="apiKey" required='true'/]
[@ww.textfield labelKey="com.scrumtech.octopus.projectName" name="projectName" required='true'/]
[@ww.textfield labelKey="com.scrumtech.octopus.version" name="version" required='true'/]
[@ww.textfield labelKey="com.scrumtech.octopus.environment" name="environment" required='true'/]