[@ww.label labelKey="com.nib.octopus.serverUrl" name="serverUrl"/]
[@ww.label labelKey="com.nib.octopus.apiKey" name="apiKey"/]
[@ww.label labelKey="com.nib.octopus.projectName" name="projectName"/]
[@ww.label labelKey="com.nib.octopus.version" name="version"/]
[@ww.label labelKey="com.nib.octopus.environment" name="environment"/]
